### ISSUE TITLE
Videos from Uwatchfree are not coming in Show Media

### ISSUE THREAD

**Issue by tushargoyal22** [twosevenxyz/extension-modal#9]
Uwatchfree movies, a popular website
https://www.uwatchfree.bz/2020/04/money-heist-2020-season-4-complete/
Video is not visible on Show media on two seven extension on pages of this website

Could you get it working for videos on this website?

**Comment by gurupras** [comment]
Closing this issue as everything seems to be working as intended. Feel free to open if you're still facing issues.
